import XCTest
import ZhuwenPacks
@testable import ZhuwenCore

// Decodes the vendored gate-vectors.json (generated by the Go reference gate).
private struct VectorSuite: Decodable {
    struct Config: Decodable {
        let maxNewTypes: Int
        let maxNewTokenRatio: Double
        let minRecurrence: Int
        let minCoverage: Double
    }
    struct Tok: Decodable {
        let k: String
        let id: Int
        let text: String
        let gloss: String?
        let first: Bool?
    }
    struct Expect: Decodable {
        let pass: Bool
        let denomTokens: Int
        let newTokens: Int
        let coverageBps: Int
        let newTypeIDs: [Int]
        let codes: [String]
    }
    struct Vector: Decodable {
        let name: String
        let tokens: [Tok]
        let known: [Int]
        let frontier: [Int]
        let grammar: [String]
        let maxWordID: Int
        let expect: Expect

        func gateTokens() -> [GateToken] {
            tokens.map { t in
                switch t.k {
                case "word": return .word(t.id, t.text)
                case "literal": return .literal(t.text)
                case "proper": return GateToken(kind: .properNoun, text: t.text, gloss: t.gloss ?? "", first: t.first ?? false)
                default: fatalError("unknown token kind \(t.k)")
                }
            }
        }
        func band() -> Band { Band(known: Set(known), frontier: Set(frontier), grammar: Set(grammar)) }
    }
    let config: Config
    let vectors: [Vector]
}

final class CoverageGateTests: XCTestCase {

    // MARK: - Shared Go/Swift vector suite (handoff §7: one vector set, two implementations)

    func testSwiftGateReproducesReferenceVectors() throws {
        let data = try Data(contentsOf: Fixtures.gateVectors)
        let suite = try JSONDecoder().decode(VectorSuite.self, from: data)
        let cfg = GateConfig(maxNewTypes: suite.config.maxNewTypes,
                             maxNewTokenRatio: suite.config.maxNewTokenRatio,
                             minRecurrence: suite.config.minRecurrence,
                             minCoverage: suite.config.minCoverage)
        XCTAssertGreaterThan(suite.vectors.count, 5, "vector suite looks empty")

        for v in suite.vectors {
            let r = CoverageGate.evaluate(tokens: v.gateTokens(), band: v.band(),
                                          maxWordID: v.maxWordID, config: cfg)
            XCTAssertEqual(r.pass, v.expect.pass, "\(v.name): pass (reasons \(r.reasons))")
            XCTAssertEqual(r.denomTokens, v.expect.denomTokens, "\(v.name): denom")
            XCTAssertEqual(r.newTokens, v.expect.newTokens, "\(v.name): newTokens")
            XCTAssertEqual(r.coverageBps, v.expect.coverageBps, "\(v.name): coverageBps")
            XCTAssertEqual(r.codes, v.expect.codes, "\(v.name): codes")
            if v.expect.pass {
                XCTAssertEqual(r.candidate?.newTypeIDs, v.expect.newTypeIDs, "\(v.name): newTypeIDs")
            } else {
                XCTAssertNil(r.candidate, "\(v.name): failing result must carry no candidate (I1)")
                XCTAssertTrue(v.expect.newTypeIDs.isEmpty)
            }
        }
    }

    // MARK: - I1 structural guarantee

    func testOnlyEvaluateProducesACandidate() {
        // A failing evaluation yields no StoryCandidate; a passing one does. StoryCandidate's
        // init is private, so evaluate() is the ONLY producer (mirrors the Go external test).
        let fail = CoverageGate.evaluate(tokens: [.literal("太")], band: Band(known: [1]), maxWordID: 1)
        XCTAssertFalse(fail.pass)
        XCTAssertNil(fail.candidate)

        let toks = Array(repeating: GateToken.word(1, "山"), count: 200)
        let pass = CoverageGate.evaluate(tokens: toks, band: Band(known: [1]), maxWordID: 1)
        XCTAssertTrue(pass.pass)
        XCTAssertEqual(pass.candidate?.coverage, 1.0)
        XCTAssertEqual(pass.candidate?.coverageBps, 10_000)
        XCTAssertTrue(pass.candidate?.coverageBitmap.test(1) ?? false)
    }

    func testBaselinePassMatchesFactory() {
        // 197 known + 3 frontier ⇒ 98.5% coverage, one new type. (Mirrors Go TestGatePassBaseline.)
        var toks = Array(repeating: GateToken.word(1, "山"), count: 197)
        toks += Array(repeating: GateToken.word(4, "坚持"), count: 3)
        let r = CoverageGate.evaluate(tokens: toks, band: Band(known: [1], frontier: [4]), maxWordID: 4)
        XCTAssertTrue(r.pass, "reasons: \(r.reasons)")
        XCTAssertEqual(r.candidate?.newTypeIDs, [4])
        XCTAssertEqual(r.coverageBps, 9850)
        XCTAssertEqual(r.candidate?.typeCount, 2)
    }

    // MARK: - Randomized property test (I1)

    // A tiny deterministic LCG so the property test is reproducible.
    private struct LCG: RandomNumberGenerator {
        var s: UInt64
        mutating func next() -> UInt64 { s = s &* 6364136223846793005 &+ 1442695040888963407; return s }
    }

    func testGateAgreesWithIndependentBudgetCheck() {
        var rng = LCG(s: 0x1234_5678_9abc_def0) // fixed seed
        let knownIDs = Array(1...20)
        let frontierIDs = Array(21...40)

        for _ in 0..<400 {
            // Build a random story: known filler + up to 12 "new" frontier words at random
            // multiplicities, occasionally an out-of-band literal. Non-marker text avoids
            // the grammar gate so this isolates the lexical budgets.
            var tokens: [GateToken] = []
            let fillerCount = Int.random(in: 50...300, using: &rng)
            for _ in 0..<fillerCount { tokens.append(.word(knownIDs.randomElement(using: &rng)!, "字")) }

            let newTypeCount = Int.random(in: 0...12, using: &rng)
            var usedNew = Set<Int>()
            var chosen = frontierIDs.shuffled(using: &rng)
            for i in 0..<newTypeCount {
                let id = chosen[i]
                usedNew.insert(id)
                let occ = Int.random(in: 1...5, using: &rng)
                for _ in 0..<occ { tokens.append(.word(id, "字")) }
            }
            let literalCount = Int.random(in: 0...2, using: &rng)
            for _ in 0..<literalCount { tokens.append(.literal("太")) }
            tokens.shuffle(using: &rng)

            // Independent expectation.
            var occ: [Int: Int] = [:]
            var denom = 0, literals = 0
            for t in tokens {
                switch t.kind {
                case .word: denom += 1; occ[t.wordID, default: 0] += 1
                case .literal: denom += 1; literals += 1
                case .properNoun: break
                }
            }
            let newTokens = usedNew.reduce(0) { $0 + (occ[$1] ?? 0) } + literals
            var expected = Set<String>()
            if literals > 0 { expected.insert(GateCode.literalOutOfLexicon) }
            if usedNew.count > 8 { expected.insert(GateCode.typeBudget) }
            if denom > 0 && Double(newTokens) / Double(denom) > 0.02 { expected.insert(GateCode.tokenBudget) }
            if usedNew.contains(where: { (occ[$0] ?? 0) < 3 }) { expected.insert(GateCode.recurrence) }
            // All new words are frontier by construction ⇒ no frontier code.

            let r = CoverageGate.evaluate(tokens: tokens, band: Band(known: Set(knownIDs), frontier: Set(frontierIDs)), maxWordID: 40)
            XCTAssertEqual(Set(r.codes), expected, "codes mismatch for denom=\(denom) new=\(usedNew.count) newTok=\(newTokens)")
            XCTAssertEqual(r.pass, expected.isEmpty)
        }
    }
}
