import Foundation
import ZhuwenPacks

enum Fixtures {
    static var dir: URL {
        URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .deletingLastPathComponent()
            .deletingLastPathComponent()
            .appendingPathComponent("Fixtures")
    }

    static func publicKey() throws -> Minisign.PublicKey {
        let text = try String(contentsOf: dir.appendingPathComponent("zhuwen-dev.pub"), encoding: .utf8)
        return try Minisign.PublicKey(file: text)
    }

    /// The shared Go/Swift coverage-gate vector suite (handoff §7), generated by the factory.
    static var gateVectors: URL { dir.appendingPathComponent("gate-vectors.json") }

    static func store() throws -> PackStore {
        try PackStore(url: dir.appendingPathComponent("fixture-a2-v0.zpack"), publicKey: try publicKey())
    }
}
